# 09 Feature Extraction

## One Hot Encoding pada Categorical / Nominal Variables

One Hot Encoding merepresentasikan setiap nilai dari suatu feature (explanatory variable) sebagai nilai biner (binary).

#### Dataset

In [14]:
X = [
    {'kota': 'Jakarta'},
    {'kota': 'Bandung'},
    {'kota': 'Surabaya'},
]

#### One Hot Encoding dengan DictVectorizer

One Hot Encoding dapat diterapkan dengan memanfatkan `DictVectorizer`.

In [15]:
from sklearn.feature_extraction import DictVectorizer
onehot_encoder = DictVectorizer()

In [16]:
encoded_X = onehot_encoder.fit_transform(X).toarray()
encoded_X

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [18]:
for x, encoded in zip(X, encoded_X):
    print(f'{x["kota"]} -> {encoded}')

Jakarta -> [0. 1. 0.]
Bandung -> [1. 0. 0.]
Surabaya -> [0. 0. 1.]


## Standarisasi Features

In [22]:
import numpy as np

X = np.array([[1., 1., 6., 14., 10.0, 2.], 
              [1., 1., 14., 16., 11., 16.],
              [1., 4., 16., 3., 1., 12.]])

X

array([[ 1.,  1.,  6., 14., 10.,  2.],
       [ 1.,  1., 14., 16., 11., 16.],
       [ 1.,  4., 16.,  3.,  1., 12.]])

In [23]:
from sklearn import preprocessing

preprocessing.scale(X)

array([[ 0.        , -0.70710678, -1.38873015,  0.52489066,  0.59299945,
        -1.35873244],
       [ 0.        , -0.70710678,  0.46291005,  0.87481777,  0.81537425,
         1.01904933],
       [ 0.        ,  1.41421356,  0.9258201 , -1.39970842, -1.4083737 ,
         0.33968311]])

## Bag of Words sebagai representasi text

In [25]:
corpus = [
    'La Liga talking points',
    'Premier League talking points',
    'Talking points from the weekend Serie A matches'
]